<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { font-family: DejaVu Sans, sans-serif; }
  body { color: #1f2937; font-size: 10px; margin: 0; }
  .wrap { padding: 26px 30px; }
  .head td { vertical-align: top; }
  .brand { font-size: 11px; font-weight: bold; color: #0d1b3e; }
  .muted { color: #6b7280; font-size: 9px; }
  .title { font-size: 20px; font-weight: bold; color: #0d1b3e; text-align: right; }
  table { width: 100%; border-collapse: collapse; }
  .kpis { margin-top: 16px; }
  .kpis td { width: 25%; border: 1px solid #e7ecf7; background: #f5f7fc; padding: 8px 10px; }
  .kpi-val { font-size: 13px; font-weight: bold; color: #0d1b3e; }
  .items { margin-top: 16px; }
  .items th { background: #0d1b3e; color: #fff; text-align: left; padding: 6px 7px; font-size: 9px; }
  .items td { padding: 5px 7px; border-bottom: 1px solid #eef1f8; font-size: 9px; }
  .items tr:nth-child(even) td { background: #f9fbff; }
  .right { text-align: right; }
  .neg { color: #dc2626; }
  .totals td { background: #e6efff !important; font-weight: bold; color: #0d1b3e; border-top: 2px solid #1466ff; }
  .foot { margin-top: 20px; border-top: 1px solid #eef1f8; padding-top: 10px; color: #6b7280; font-size: 8px; }
</style>
</head>
<body>
@php
  $cell = function ($v, $format) {
      if ($format === 'money') {
          return 'RM ' . number_format((float) $v, 2);
      }
      if ($format === 'int') {
          return number_format((int) $v);
      }
      if ($format === 'percent') {
          return number_format((float) $v, 2) . '%';
      }
      return $v;
  };
@endphp
<div class="wrap">
  <table class="head">
    <tr>
      <td>
        <img src="{{ $company->logoPath() }}" alt="" style="height:74px; width:auto; margin-bottom:6px">
        <div class="brand">{{ $company->name }}</div>
        <div class="muted">
          {{ $company->address }}<br>
          {{ $company->postcode }} {{ $company->city }}, {{ $company->state }}<br>
          {{ $company->phone }} · {{ $company->email }}
        </div>
      </td>
      <td>
        <div class="title">{{ strtoupper($report['title']) }}</div>
        <div class="muted" style="text-align:right">
          Period: {{ $report['from']->format('d M Y') }} — {{ $report['to']->format('d M Y') }}<br>
          Generated: {{ now()->format('d M Y, H:i') }}<br>
          {{ count($report['rows']) }} row(s)
        </div>
      </td>
    </tr>
  </table>

  <table class="kpis">
    <tr>
      @foreach ($report['kpis'] as $kpi)
        <td>
          <div class="muted">{{ $kpi['label'] }}</div>
          <div class="kpi-val">{{ $kpi['value'] }}</div>
        </td>
      @endforeach
    </tr>
  </table>

  <table class="items">
    <thead>
      <tr>
        @foreach ($report['columns'] as $col)
          <th class="{{ in_array($col['format'], ['money', 'int', 'percent']) ? 'right' : '' }}">{{ $col['label'] }}</th>
        @endforeach
      </tr>
    </thead>
    <tbody>
      @forelse ($report['rows'] as $row)
        <tr>
          @foreach ($report['columns'] as $i => $col)
            <td class="{{ in_array($col['format'], ['money', 'int', 'percent']) ? 'right' : '' }} {{ $col['format'] === 'money' && (float) ($row[$i] ?? 0) < 0 ? 'neg' : '' }}">
              {{ $cell($row[$i] ?? '', $col['format']) }}
            </td>
          @endforeach
        </tr>
      @empty
        <tr><td colspan="{{ count($report['columns']) }}" style="text-align:center;padding:16px">No data for this period.</td></tr>
      @endforelse
      @if (! empty($report['totals']))
        <tr class="totals">
          @foreach ($report['columns'] as $i => $col)
            <td class="{{ in_array($col['format'], ['money', 'int', 'percent']) ? 'right' : '' }}">
              {{ isset($report['totals'][$i]) ? (is_string($report['totals'][$i]) ? $report['totals'][$i] : $cell($report['totals'][$i], $col['format'])) : '' }}
            </td>
          @endforeach
        </tr>
      @endif
    </tbody>
  </table>

  <div class="foot">
    {{ $report['subtitle'] }} · This report is system-generated by {{ $company->name }} TAMS. Private &amp; confidential.
  </div>
</div>
</body>
</html>
